# Generated by Django 3.2 on 2023-04-09 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
