# Generated by Django 3.2 on 2023-04-09 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prints', '0003_auto_20230409_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='likes',
        ),
        migrations.AddField(
            model_name='print',
            name='likes',
            field=models.ManyToManyField(related_name='print_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
