# Generated by Django 3.2 on 2023-04-16 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prints', '0004_auto_20230409_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='print',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prints.category'),
        ),
        migrations.AlterField(
            model_name='print',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='print_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
