# Generated by Django 3.2 on 2023-04-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20230418_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
